def qa_groups():
    # Each group:
    #   english prompt variants, correct answer, wrong answer
    #   chinese prompt variants, correct answer, wrong answer
    #
    # Answers are intentionally short so the tiny model gets a clean signal.
    groups = [
        (
            ["Who was Li Bai?", "What was Li Bai known for?"],
            "Li Bai was a Chinese poet of the Tang dynasty.",
            "Li Bai was a modern scientist.",
            ["李白是谁？", "李白以什么著名？"],
            "李白是中国唐代诗人。",
            "李白是现代科学家。",
        ),
        (
            ["Who was Albert Einstein?", "What was Einstein known for?"],
            "Albert Einstein was a German-born physicist.",
            "Albert Einstein was an American politician.",
            ["爱因斯坦是谁？", "爱因斯坦以什么著名？"],
            "爱因斯坦是出生于德国的物理学家。",
            "爱因斯坦是美国政治家。",
        ),
        (
            ["Who was Isaac Newton?", "What was Newton known for?"],
            "Isaac Newton was an English physicist and mathematician.",
            "Isaac Newton was a French painter.",
            ["牛顿是谁？", "牛顿以什么著名？"],
            "牛顿是英国物理学家和数学家。",
            "牛顿是法国画家。",
        ),
        (
            ["Who was Ada Lovelace?", "What was Ada Lovelace known for?"],
            "Ada Lovelace was a pioneer of computer programming.",
            "Ada Lovelace was a Renaissance painter.",
            ["阿达·洛夫莱斯是谁？", "阿达·洛夫莱斯以什么著名？"],
            "阿达·洛夫莱斯是计算机编程先驱。",
            "阿达·洛夫莱斯是文艺复兴时期画家。",
        ),
        (
            ["Who was Alan Turing?", "What was Alan Turing known for?"],
            "Alan Turing was a British mathematician and computer scientist.",
            "Alan Turing was a Chinese poet.",
            ["图灵是谁？", "图灵以什么著名？"],
            "图灵是英国数学家和计算机科学家。",
            "图灵是中国诗人。",
        ),
        (
            ["What is artificial intelligence?", "Define artificial intelligence."],
            "Artificial intelligence is technology that enables computers to perform tasks that normally require human intelligence.",
            "Artificial intelligence is a database table.",
            ["什么是人工智能？", "请定义人工智能。"],
            "人工智能是让计算机执行通常需要人类智能任务的一种技术。",
            "人工智能是一张数据库表。",
        ),
        (
            ["What is machine learning?", "Define machine learning."],
            "Machine learning lets computers learn patterns from data.",
            "Machine learning is a web browser.",
            ["什么是机器学习？", "请定义机器学习。"],
            "机器学习让计算机从数据中学习规律。",
            "机器学习是一种网页浏览器。",
        ),
        (
            ["What is a language model?", "Define a language model."],
            "A language model predicts likely tokens from context and can generate text.",
            "A language model is a physical computer cable.",
            ["什么是语言模型？", "请定义语言模型。"],
            "语言模型根据上下文预测可能的词元，并生成文本。",
            "语言模型是一根电脑电缆。",
        ),
        (
            ["What is a transformer in machine learning?", "Define a transformer model."],
            "A transformer is a neural network architecture built around attention.",
            "A transformer is a database system.",
            ["机器学习中的 Transformer 是什么？", "请定义 Transformer 模型。"],
            "Transformer 是一种以注意力机制为核心的神经网络架构。",
            "Transformer 是一种数据库系统。",
        ),
        (
            ["What is attention in a transformer?", "What does attention do?"],
            "Attention lets a model focus on relevant parts of the input.",
            "Attention is a type of web browser.",
            ["Transformer 中的注意力是什么？", "注意力机制有什么作用？"],
            "注意力机制让模型重点关注输入中更相关的部分。",
            "注意力机制是一种网页浏览器。",
        ),
        (
            ["What is a tokenizer?", "What does a tokenizer do?"],
            "A tokenizer converts text into tokens that a model can process.",
            "A tokenizer is a graphics card.",
            ["什么是 tokenizer？", "tokenizer 有什么作用？"],
            "tokenizer 把文本转换成模型可以处理的词元。",
            "tokenizer 是一种显卡。",
        ),
        (
            ["What is BPE?", "What does BPE stand for in tokenization?"],
            "BPE is a subword tokenization method.",
            "BPE is a database protocol.",
            ["什么是 BPE？", "BPE 在分词中是什么？"],
            "BPE 是一种子词分词方法。",
            "BPE 是一种数据库协议。",
        ),
        (
            ["What is a neural network?", "Define a neural network."],
            "A neural network is a model made of connected computational layers.",
            "A neural network is a file format.",
            ["什么是神经网络？", "请定义神经网络。"],
            "神经网络是由相互连接的计算层组成的模型。",
            "神经网络是一种文件格式。",
        ),
        (
            ["What is a GPU?", "What does GPU stand for?"],
            "A GPU is a processor designed for highly parallel computation.",
            "A GPU is a text file format.",
            ["什么是 GPU？", "GPU 是什么？"],
            "GPU 是适合大规模并行计算的处理器。",
            "GPU 是一种文本文件格式。",
        ),
        (
            ["What is a CPU?", "What does CPU stand for?"],
            "A CPU is a general-purpose processor.",
            "A CPU is an image file format.",
            ["什么是 CPU？", "CPU 是什么？"],
            "CPU 是一种通用处理器。",
            "CPU 是一种图片文件格式。",
        ),
        (
            ["What is Python?", "What is the Python programming language?"],
            "Python is a general-purpose programming language.",
            "Python is a database engine.",
            ["什么是 Python？", "Python 是什么编程语言？"],
            "Python 是一种通用编程语言。",
            "Python 是一种数据库引擎。",
        ),
        (
            ["What is Git?", "What is Git used for?"],
            "Git is a version control system.",
            "Git is a web browser.",
            ["什么是 Git？", "Git 用来做什么？"],
            "Git 是一种版本控制系统。",
            "Git 是一种网页浏览器。",
        ),
        (
            ["What is GitHub?", "What is GitHub used for?"],
            "GitHub is a platform for hosting and collaborating on software repositories.",
            "GitHub is a CPU architecture.",
            ["什么是 GitHub？", "GitHub 用来做什么？"],
            "GitHub 是用于托管和协作软件代码仓库的平台。",
            "GitHub 是一种 CPU 架构。",
        ),
        (
            ["What is HTML?", "What is HTML used for?"],
            "HTML is the markup language used to structure web pages.",
            "HTML is a machine learning optimizer.",
            ["什么是 HTML？", "HTML 用来做什么？"],
            "HTML 是用于组织网页结构的标记语言。",
            "HTML 是一种机器学习优化器。",
        ),
        (
            ["What is CSS?", "What is CSS used for?"],
            "CSS is used to style web pages.",
            "CSS is a programming language for operating systems.",
            ["什么是 CSS？", "CSS 用来做什么？"],
            "CSS 用于设置网页样式。",
            "CSS 是一种操作系统编程语言。",
        ),
        (
            ["What is JSON?", "What is JSON used for?"],
            "JSON is a text format commonly used to represent structured data.",
            "JSON is a graphics card.",
            ["什么是 JSON？", "JSON 用来做什么？"],
            "JSON 是一种常用于表示结构化数据的文本格式。",
            "JSON 是一种显卡。",
        ),
        (
            ["What is a database?", "Define a database."],
            "A database is a system for storing and organizing data.",
            "A database is a programming language.",
            ["什么是数据库？", "请定义数据库。"],
            "数据库是用于存储和组织数据的系统。",
            "数据库是一种编程语言。",
        ),
        (
            ["What is the Internet?", "Define the Internet."],
            "The Internet is a global network of connected computer systems.",
            "The Internet is a single computer.",
            ["什么是互联网？", "请定义互联网。"],
            "互联网是由相互连接的计算机系统组成的全球网络。",
            "互联网是一台单独的电脑。",
        ),
        (
            ["What is gravity?", "Define gravity."],
            "Gravity is a force that attracts masses toward each other.",
            "Gravity is a type of programming language.",
            ["什么是重力？", "请定义重力。"],
            "重力是使物体相互吸引的一种力。",
            "重力是一种编程语言。",
        ),
        (
            ["What is water made of?", "What is the chemical formula of water?"],
            "Water is H2O.",
            "Water is CO2.",
            ["水由什么组成？", "水的化学式是什么？"],
            "水的化学式是 H2O。",
            "水的化学式是 CO2。",
        ),
        (
            ["How many days are in a week?", "How long is one week?"],
            "Seven days.",
            "Ten days.",
            ["一周有几天？", "一星期有多长？"],
            "七天。",
            "十天。",
        ),
        (
            ["How many months are in a year?", "How many months make one year?"],
            "Twelve months.",
            "Ten months.",
            ["一年有几个月？", "一年包含多少个月？"],
            "十二个月。",
            "十个月。",
        ),
        (
            ["What do bees make?", "What do bees produce?"],
            "Bees make honey.",
            "Bees make steel.",
            ["蜜蜂生产什么？", "蜜蜂会制造什么？"],
            "蜜蜂生产蜂蜜。",
            "蜜蜂生产钢铁。",
        ),
        (
            ["What is the opposite of hot?", "What is the opposite of hot?"],
            "Cold.",
            "Tall.",
            ["热的反义词是什么？", "什么是热的反义词？"],
            "冷。",
            "高。",
        ),
        (
            ["What is the opposite of big?", "What is opposite to big?"],
            "Small.",
            "Fast.",
            ["大的反义词是什么？", "什么是大的反义词？"],
            "小。",
            "快。",
        ),
        (
            ["What is 7 + 8?", "Calculate 7 + 8."],
            "15.",
            "9.",
            ["7 加 8 等于多少？", "计算 7 加 8。"],
            "15。",
            "9。",
        ),
        (
            ["What is 12 + 9?", "Calculate 12 + 9."],
            "21.",
            "29.",
            ["12 加 9 等于多少？", "计算 12 加 9。"],
            "21。",
            "29。",
        ),
        (
            ["What is 7 times 8?", "Calculate 7 * 8."],
            "56.",
            "84.",
            ["7 乘 8 等于多少？", "计算 7 乘 8。"],
            "56。",
            "84。",
        ),
        (
            ["What is 72 divided by 8?", "Calculate 72 / 8."],
            "9.",
            "18.",
            ["72 除以 8 等于多少？", "计算 72 除以 8。"],
            "9。",
            "18。",
        ),
        (
            ["Translate 'robot' into Chinese.", "What is the Chinese word for robot?"],
            "机器人。",
            "数据库。",
            ["把“robot”翻译成中文。", "robot 的中文是什么？"],
            "机器人。",
            "数据库。",
        ),
        (
            ["Translate 'data' into Chinese.", "What is the Chinese word for data?"],
            "数据。",
            "软件。",
            ["把“data”翻译成中文。", "data 的中文是什么？"],
            "数据。",
            "软件。",
        ),
        (
            ["Translate 'software' into Chinese.", "What is the Chinese word for software?"],
            "软件。",
            "硬件。",
            ["把“software”翻译成中文。", "software 的中文是什么？"],
            "软件。",
            "硬件。",
        ),
        (
            ["Translate 'hardware' into Chinese.", "What is the Chinese word for hardware?"],
            "硬件。",
            "软件。",
            ["把“hardware”翻译成中文。", "hardware 的中文是什么？"],
            "硬件。",
            "软件。",
        ),
        (
            ["Translate 'computer' into Chinese.", "What is the Chinese word for computer?"],
            "电脑。",
            "机器人。",
            ["把“computer”翻译成中文。", "computer 的中文是什么？"],
            "电脑。",
            "机器人。",
        ),
        (
            ["Translate 'language model' into Chinese.", "What is the Chinese translation of language model?"],
            "语言模型。",
            "机器视觉。",
            ["把“language model”翻译成中文。", "language model 的中文是什么？"],
            "语言模型。",
            "机器视觉。",
        ),
        (
            ["Translate 'attention' into Chinese.", "What is the Chinese translation of attention?"],
            "注意力。",
            "数据库。",
            ["把“attention”翻译成中文。", "attention 的中文是什么？"],
            "注意力。",
            "数据库。",
        ),
        (
            ["Translate 'drone' into Chinese.", "What is the Chinese word for drone?"],
            "无人机。",
            "数据库。",
            ["把“drone”翻译成中文。", "drone 的中文是什么？"],
            "无人机。",
            "数据库。",
        ),
    ]
    return groups
